management.endpoints.web.exposure.include=*
management.endpoint.metrics.enabled=true

# Connect directly using Docker's internal container routing network
management.metrics.export.graphite.enabled=true
management.metrics.export.graphite.host=graphite-server
management.metrics.export.graphite.port=2003

# Force immediate metric streaming delivery
management.metrics.export.graphite.step=5s