# Expose health checks for Nagios
management.endpoints.web.exposure.include=health,info,metrics

# Tell Micrometer to send metrics to our Dockerized Graphite
management.metrics.export.graphite.enabled=true
management.metrics.export.graphite.host=host.docker.internal
management.metrics.export.graphite.port=2004